/**
 * プリセットのタグカテゴリとタグ。
 *
 * ここに定義したものは初回起動時（およびプリセット更新時）に DB へ「データとして」追加される。
 * 以降はユーザーが自由に名前変更・非表示・追加できる。ID は安定キー（例: "terrain.ridge"）なので、
 * 提案ルールなどから参照でき、将来プリセットを増やしても既存データと衝突しない。
 *
 * 新しいタグを追加するときは配列の末尾に足し、PRESET_VERSION を上げるだけでよい。
 */

export const PRESET_VERSION = 1;

type PresetTag = [key: string, label: string, aliases?: string[]];

interface PresetCategory {
  key: string;
  name: string;
  icon: string;
  description: string;
  tags: PresetTag[];
}

export const PRESET_CATEGORIES: PresetCategory[] = [
  {
    key: 'terrain',
    name: '地形・ルート',
    icon: '⛰️',
    description: '歩く道の地形や環境',
    tags: [
      ['ridge', '尾根'],
      ['skyline', '稜線'],
      ['stream', '沢沿い'],
      ['gorge', '渓谷'],
      ['forest', '樹林帯'],
      ['rockridge', '岩稜'],
      ['rocky', '岩場'],
      ['gare', 'ガレ場'],
      ['zare', 'ザレ場'],
      ['marsh', '湿原'],
      ['meadow', '草原'],
      ['volcanic', '火山地形'],
      ['gravel', '砂礫地'],
      ['snowfield', '雪渓'],
      ['forestroad', '林道'],
      ['paved', '舗装路'],
      ['stairs', '階段'],
      ['boardwalk', '木道'],
    ],
  },
  {
    key: 'technical',
    name: '技術要素',
    icon: '🧗',
    description: '通過に技術や注意が必要な要素',
    tags: [
      ['chain', '鎖場', ['クサリ']],
      ['rope', 'ロープ'],
      ['ladder', '梯子', ['はしご', 'ハシゴ']],
      ['steepup', '急登'],
      ['steepdown', '急下降'],
      ['threepoint', '三点支持'],
      ['scramble', '簡単な岩登り'],
      ['crossing', '渡渉'],
      ['wading', '徒渉'],
      ['traverse', 'トラバース'],
      ['knife', '痩せ尾根', ['やせ尾根']],
      ['collapse', '崩落地'],
      ['bush', '藪', ['ヤブ', 'やぶ']],
      ['routefind', '道迷い注意箇所'],
      ['crampon', 'アイゼン必要'],
    ],
  },
  {
    key: 'scenery',
    name: '景観',
    icon: '🌄',
    description: '見どころ・景色',
    tags: [
      ['fuji', '富士山展望', ['富士山']],
      ['alps', 'アルプス展望'],
      ['mountains', '山並み'],
      ['panorama', '360°展望', ['大展望']],
      ['sea', '海'],
      ['lake', '湖'],
      ['waterfall', '滝'],
      ['brook', '渓流'],
      ['cloudsea', '雲海'],
      ['nightview', '夜景'],
      ['sunrise', '日の出', ['ご来光']],
      ['sunset', '夕日'],
      ['autumn', '紅葉'],
      ['greenery', '新緑'],
      ['flowers', '花', ['高山植物']],
      ['snowscape', '雪景色'],
      ['bigtree', '巨木'],
      ['oddrock', '奇岩'],
    ],
  },
  {
    key: 'style',
    name: '山行スタイル',
    icon: '🥾',
    description: 'ルートの取り方・泊まり方',
    tags: [
      ['outandback', 'ピストン', ['往復']],
      ['loop', '周回'],
      ['traverse', '縦走'],
      ['station2station', '駅to駅'],
      ['bus2station', 'バスto駅'],
      ['ropeway', 'ロープウェイ利用'],
      ['cablecar', 'ケーブルカー利用'],
      ['hut', '山小屋泊'],
      ['tent', 'テント泊'],
      ['dayhike', '日帰り'],
      ['nightbefore', '前夜泊'],
    ],
  },
  {
    key: 'season',
    name: '季節適性',
    icon: '🍁',
    description: '行きやすい・楽しい時期',
    tags: [
      ['spring', '春向き'],
      ['summer', '夏向き'],
      ['autumn', '秋向き'],
      ['winter', '冬向き'],
      ['allyear', '通年'],
      ['latesnow', '残雪期'],
      ['midwinter', '厳冬期'],
      ['foliage', '紅葉期'],
      ['flower', '花期'],
      ['freshgreen', '新緑期'],
    ],
  },
  {
    key: 'stamina',
    name: '体力要素',
    icon: '💪',
    description: '体力的な負荷の感覚',
    tags: [
      ['light', '軽め'],
      ['normal', '普通'],
      ['solid', 'しっかり'],
      ['long', 'ロング'],
      ['verylong', '超ロング'],
      ['bigascent', '累積標高大'],
      ['steep', '急登中心'],
    ],
  },
  {
    key: 'difficulty',
    name: '技術難度',
    icon: '📶',
    description: 'ルート全体の難しさの区分',
    tags: [
      ['hiking', 'ハイキング'],
      ['general', '一般登山道'],
      ['caution', '注意箇所あり'],
      ['rocky', '岩場あり'],
      ['advanced', '上級者向け'],
      ['variation', 'バリエーションルート'],
    ],
  },
  {
    key: 'access',
    name: 'アクセス',
    icon: '🚃',
    description: '登山口までの行きやすさ',
    tags: [
      ['walkfromstation', '駅から徒歩'],
      ['bus', 'バス利用'],
      ['taxi', 'タクシー利用'],
      ['car', '車向き'],
      ['parking', '駐車場あり'],
      ['public', '公共交通向き'],
      ['earlyhard', '早朝アクセス難'],
      ['fewbus', 'バス本数少'],
      ['seasonalbus', '季節運行バス'],
    ],
  },
  {
    key: 'facility',
    name: '施設',
    icon: '🏠',
    description: '山中・登山口の施設',
    tags: [
      ['hut', '山小屋'],
      ['shelter', '避難小屋'],
      ['toilet', 'トイレ'],
      ['water', '水場'],
      ['shop', '売店'],
      ['restaurant', '食事処'],
      ['onsen', '温泉'],
      ['camp', 'キャンプ場'],
    ],
  },
  {
    key: 'after',
    name: '下山後・周辺の楽しみ',
    icon: '♨️',
    description: '下山後や周辺で楽しめること',
    tags: [
      ['onsen', '温泉', ['日帰り湯', '日帰り温泉']],
      ['yamameshi', '山ごはん'],
      ['soba', '蕎麦', ['そば']],
      ['cafe', 'カフェ'],
      ['sightseeing', '観光'],
      ['pilgrimage', '聖地巡礼'],
      ['roadstation', '道の駅'],
      ['beer', 'ビール・地酒'],
    ],
  },
  {
    key: 'crowd',
    name: '混雑傾向',
    icon: '👥',
    description: '人の多さの傾向',
    tags: [
      ['quiet', '静か'],
      ['few', '人少なめ'],
      ['normal', '普通'],
      ['popular', '人気'],
      ['crowded', 'かなり混む'],
    ],
  },
  {
    key: 'danger',
    name: '危険・注意要素',
    icon: '⚠️',
    description: '気をつけたいリスク',
    tags: [
      ['bear', 'クマ'],
      ['leech', 'ヒル'],
      ['wasp', 'ハチ'],
      ['tick', 'マダニ'],
      ['rockfall', '落石'],
      ['fall', '滑落'],
      ['flood', '増水'],
      ['mud', 'ぬかるみ'],
      ['ice', '凍結'],
      ['wind', '強風'],
      ['thunder', '雷'],
      ['heat', '暑さ'],
      ['nowater', '水場不足'],
      ['lost', '道迷い'],
      ['altitude', '高山病'],
    ],
  },
  {
    key: 'feature',
    name: '山そのものの特徴',
    icon: '🗻',
    description: '山の成り立ちや性格',
    tags: [
      ['isolated', '独立峰'],
      ['range', '連峰'],
      ['volcano', '火山'],
      ['stratovolcano', '成層火山'],
      ['lavadome', '溶岩ドーム'],
      ['rockpeak', '岩峰'],
      ['satoyama', '里山'],
      ['low', '低山'],
      ['high', '高山'],
      ['active', '活火山'],
    ],
  },
  {
    key: 'title',
    name: '選定・称号',
    icon: '🏅',
    description: '百名山などの選定',
    tags: [
      ['hyaku', '日本百名山', ['百名山']],
      ['nihyaku', '日本二百名山', ['二百名山']],
      ['sanbyaku', '日本三百名山', ['三百名山']],
      ['prefhighest', '都道府県最高峰'],
      ['hana', '花の百名山'],
      ['shinhana', '新・花の百名山'],
      ['local', 'ご当地百名山'],
      ['triangulation', '一等三角点'],
    ],
  },
  {
    key: 'preference',
    name: '個人的な好み',
    icon: '💚',
    description: '自分にとっての魅力',
    tags: [
      ['ridgewalk', '尾根歩きが楽しい'],
      ['view', '景色重視'],
      ['hearty', '歩きごたえあり'],
      ['quiet', '静かな山'],
      ['adventure', '冒険感'],
      ['achievement', '達成感'],
      ['beginnerfriendly', '初心者と行きやすい'],
      ['solo', 'ソロ向き'],
      ['again', 'また歩きたい'],
      ['photo', '写真映え'],
      ['rainyok', '雨でも楽しめる'],
    ],
  },
];

export const categoryId = (key: string) => `cat.${key}`;
export const presetTagId = (catKey: string, tagKey: string) => `${catKey}.${tagKey}`;

/** 提案ルールなどから参照するよく使うタグID */
export const T = {
  ridge: 'terrain.ridge',
  skyline: 'terrain.skyline',
  rockridge: 'terrain.rockridge',
  rocky: 'terrain.rocky',
  stream: 'terrain.stream',
  gorge: 'terrain.gorge',
  chain: 'technical.chain',
  ladder: 'technical.ladder',
  scramble: 'technical.scramble',
  threepoint: 'technical.threepoint',
  knife: 'technical.knife',
  steepup: 'technical.steepup',
  waterfall: 'scenery.waterfall',
  brook: 'scenery.brook',
  fuji: 'scenery.fuji',
  alps: 'scenery.alps',
  panorama: 'scenery.panorama',
  mountains: 'scenery.mountains',
  sea: 'scenery.sea',
  cloudsea: 'scenery.cloudsea',
  lake: 'scenery.lake',
  styleTraverse: 'style.traverse',
  styleLoop: 'style.loop',
  station2station: 'style.station2station',
  bus2station: 'style.bus2station',
  dayhike: 'style.dayhike',
  hut: 'style.hut',
  tent: 'style.tent',
  seasonSpring: 'season.spring',
  seasonSummer: 'season.summer',
  seasonAutumn: 'season.autumn',
  seasonWinter: 'season.winter',
  seasonAllyear: 'season.allyear',
  seasonLatesnow: 'season.latesnow',
  seasonMidwinter: 'season.midwinter',
  seasonFoliage: 'season.foliage',
  seasonFlower: 'season.flower',
  seasonFreshgreen: 'season.freshgreen',
  staminaLight: 'stamina.light',
  staminaNormal: 'stamina.normal',
  staminaSolid: 'stamina.solid',
  staminaLong: 'stamina.long',
  staminaVerylong: 'stamina.verylong',
  staminaBigascent: 'stamina.bigascent',
  staminaSteep: 'stamina.steep',
  diffHiking: 'difficulty.hiking',
  diffGeneral: 'difficulty.general',
  diffCaution: 'difficulty.caution',
  diffRocky: 'difficulty.rocky',
  diffAdvanced: 'difficulty.advanced',
  diffVariation: 'difficulty.variation',
  walkFromStation: 'access.walkfromstation',
  bus: 'access.bus',
  taxi: 'access.taxi',
  car: 'access.car',
  parking: 'access.parking',
  publicTransport: 'access.public',
  earlyHard: 'access.earlyhard',
  facilityOnsen: 'facility.onsen',
  afterOnsen: 'after.onsen',
  crowdQuiet: 'crowd.quiet',
  crowdFew: 'crowd.few',
  crowdNormal: 'crowd.normal',
  crowdPopular: 'crowd.popular',
  crowdCrowded: 'crowd.crowded',
  prefRidgewalk: 'preference.ridgewalk',
  prefView: 'preference.view',
  prefHearty: 'preference.hearty',
  prefQuiet: 'preference.quiet',
  prefAdventure: 'preference.adventure',
  prefBeginner: 'preference.beginnerfriendly',
} as const;

/** 比較画面などで「主な特徴」として扱うカテゴリ */
export const FEATURE_CATEGORY_KEYS = ['terrain', 'scenery', 'style', 'feature', 'title'];
export const DANGER_CATEGORY_KEYS = ['danger', 'technical'];
export const AFTER_CATEGORY_KEYS = ['after', 'facility'];
export const ACCESS_CATEGORY_KEYS = ['access'];
